In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_excel("FLOATWELL LIMITS.xlsx")

In [3]:
data

Unnamed: 0 LS01 Unnamed: 2 LS02 Unnamed: 4 LS03 Unnamed: 6 LS04  \
0          NaN    ↑          ↓    ↑          ↓    ↑          ↓    ↑   
1       438.66   ON         ON   ON         ON   ON         ON   ON   
2       438.65   ON         ON   ON         ON   ON         ON   ON   
3       438.64   ON         ON   ON         ON   ON         ON   ON   
4       438.63   ON         ON   ON         ON   ON         ON   ON   
..         ...  ...        ...  ...        ...  ...        ...  ...   
66      438.01   ON         ON  NaN        NaN  NaN        NaN  NaN   
67      438.00  NaN         ON  NaN        NaN  NaN        NaN  NaN   
68      437.99  NaN         ON  NaN        NaN  NaN        NaN  NaN   
69      437.98  NaN         ON  NaN        NaN  NaN        NaN  NaN   
70      438.97  NaN        NaN  NaN        NaN  NaN        NaN  NaN   

   Unnamed: 8 LS05  ... LS29 Unnamed: 58 LS30 Unnamed: 60 LS31 Unnamed: 62  \
0           ↓    ↑  ...    ↑           ↓    ↑           ↓    ↑           ↓   
1          ON   ON  ...   ON          ON   ON          ON   ON          ON   
2          ON   ON  ...   ON          ON   ON          ON   ON          ON   
3          ON   ON  ...   ON          ON   ON          ON   ON          ON   
4          ON   ON  ...   ON          ON   ON          ON   ON          ON   
..        ...  ...  ...  ...         ...  ...         ...  ...         ...   
66        NaN  NaN  ...  NaN         NaN  NaN         NaN  NaN         NaN   
67        NaN  NaN  ...  NaN         NaN  NaN         NaN  NaN         NaN   
68        NaN  NaN  ...  NaN         NaN  NaN         NaN  NaN         NaN   
69        NaN  NaN  ...  NaN         NaN  NaN         NaN  NaN         NaN   
70        NaN  NaN  ...  NaN         NaN  NaN         NaN  NaN         NaN   

   LS32 Unnamed: 64 Open Close  
0     ↑           ↓  NaN   NaN  
1    ON          ON  NaN   NaN  
2   NaN          ON  NaN   NaN  
3   NaN          ON  NaN   NaN  
4   NaN          ON  NaN   NaN  
..  ...         ...  ...   ...  
66  NaN         NaN  NaN   NaN  
67  NaN         NaN  NaN   NaN  
68  NaN         NaN  NaN   NaN  
69  NaN         NaN  NaN   NaN  
70  NaN         NaN  NaN   NaN  

[71 rows x 67 columns]

In [4]:
data.drop(axis= 0, index = 0,inplace=True)

In [5]:
data.fillna(0, inplace=True)

In [6]:
data

Unnamed: 0 LS01 Unnamed: 2 LS02 Unnamed: 4 LS03 Unnamed: 6 LS04  \
1       438.66   ON         ON   ON         ON   ON         ON   ON   
2       438.65   ON         ON   ON         ON   ON         ON   ON   
3       438.64   ON         ON   ON         ON   ON         ON   ON   
4       438.63   ON         ON   ON         ON   ON         ON   ON   
5       438.62   ON         ON   ON         ON   ON         ON   ON   
..         ...  ...        ...  ...        ...  ...        ...  ...   
66      438.01   ON         ON    0          0    0          0    0   
67      438.00    0         ON    0          0    0          0    0   
68      437.99    0         ON    0          0    0          0    0   
69      437.98    0         ON    0          0    0          0    0   
70      438.97    0          0    0          0    0          0    0   

   Unnamed: 8 LS05  ... LS29 Unnamed: 58 LS30 Unnamed: 60 LS31 Unnamed: 62  \
1          ON   ON  ...   ON          ON   ON          ON   ON          ON   
2          ON   ON  ...   ON          ON   ON          ON   ON          ON   
3          ON   ON  ...   ON          ON   ON          ON   ON          ON   
4          ON   ON  ...   ON          ON   ON          ON   ON          ON   
5          ON   ON  ...   ON          ON   ON          ON   ON          ON   
..        ...  ...  ...  ...         ...  ...         ...  ...         ...   
66          0    0  ...    0           0    0           0    0           0   
67          0    0  ...    0           0    0           0    0           0   
68          0    0  ...    0           0    0           0    0           0   
69          0    0  ...    0           0    0           0    0           0   
70          0    0  ...    0           0    0           0    0           0   

   LS32 Unnamed: 64 Open Close  
1    ON          ON  0.0   0.0  
2     0          ON  0.0   0.0  
3     0          ON  0.0   0.0  
4     0          ON  0.0   0.0  
5     0           0  0.0   0.0  
..  ...         ...  ...   ...  
66    0           0  0.0   0.0  
67    0           0  0.0   0.0  
68    0           0  0.0   0.0  
69    0           0  0.0   0.0  
70    0           0  0.0   0.0  

[70 rows x 67 columns]

In [7]:
data = data.replace("ON", 1)

In [8]:
data

Unnamed: 0  LS01  Unnamed: 2  LS02  Unnamed: 4  LS03  Unnamed: 6  LS04  \
1       438.66     1           1     1           1     1           1     1   
2       438.65     1           1     1           1     1           1     1   
3       438.64     1           1     1           1     1           1     1   
4       438.63     1           1     1           1     1           1     1   
5       438.62     1           1     1           1     1           1     1   
..         ...   ...         ...   ...         ...   ...         ...   ...   
66      438.01     1           1     0           0     0           0     0   
67      438.00     0           1     0           0     0           0     0   
68      437.99     0           1     0           0     0           0     0   
69      437.98     0           1     0           0     0           0     0   
70      438.97     0           0     0           0     0           0     0   

    Unnamed: 8  LS05  ...  LS29  Unnamed: 58  LS30  Unnamed: 60  LS31  \
1            1     1  ...     1            1     1            1     1   
2            1     1  ...     1            1     1            1     1   
3            1     1  ...     1            1     1            1     1   
4            1     1  ...     1            1     1            1     1   
5            1     1  ...     1            1     1            1     1   
..         ...   ...  ...   ...          ...   ...          ...   ...   
66           0     0  ...     0            0     0            0     0   
67           0     0  ...     0            0     0            0     0   
68           0     0  ...     0            0     0            0     0   
69           0     0  ...     0            0     0            0     0   
70           0     0  ...     0            0     0            0     0   

    Unnamed: 62  LS32  Unnamed: 64  Open  Close  
1             1     1            1   0.0    0.0  
2             1     0            1   0.0    0.0  
3             1     0            1   0.0    0.0  
4             1     0            1   0.0    0.0  
5             1     0            0   0.0    0.0  
..          ...   ...          ...   ...    ...  
66            0     0            0   0.0    0.0  
67            0     0            0   0.0    0.0  
68            0     0            0   0.0    0.0  
69            0     0            0   0.0    0.0  
70            0     0            0   0.0    0.0  

[70 rows x 67 columns]

In [9]:
data.columns

Index(['Unnamed: 0', 'LS01', 'Unnamed: 2', 'LS02', 'Unnamed: 4', 'LS03',
       'Unnamed: 6', 'LS04', 'Unnamed: 8', 'LS05', 'Unnamed: 10', 'LS06',
       'Unnamed: 12', 'LS07', 'Unnamed: 14', 'LS08', 'Unnamed: 16', 'LS09',
       'Unnamed: 18', 'LS10', 'Unnamed: 20', 'LS11', 'Unnamed: 22', 'LS12',
       'Unnamed: 24', 'LS13', 'Unnamed: 26', 'LS14', 'Unnamed: 28', 'LS15',
       'Unnamed: 30', 'LS16', 'Unnamed: 32', 'LS17', 'Unnamed: 34', 'LS18',
       'Unnamed: 36', 'LS19', 'Unnamed: 38', 'LS20', 'Unnamed: 40', 'LS21',
       'Unnamed: 42', 'LS22', 'Unnamed: 44', 'LS23', 'Unnamed: 46', 'LS24',
       'Unnamed: 48', 'LS25', 'Unnamed: 50', 'LS26', 'Unnamed: 52', 'LS27',
       'Unnamed: 54', 'LS28', 'Unnamed: 56', 'LS29', 'Unnamed: 58', 'LS30',
       'Unnamed: 60', 'LS31', 'Unnamed: 62', 'LS32', 'Unnamed: 64', 'Open',
       'Close'],
      dtype='object')

In [10]:
data.rename(columns={'Unnamed: 0': "WaterLevel"}, inplace=True)

In [11]:
data['Open']

1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
     ... 
66    0.0
67    0.0
68    0.0
69    0.0
70    0.0
Name: Open, Length: 70, dtype: float64

In [12]:
data

WaterLevel  LS01  Unnamed: 2  LS02  Unnamed: 4  LS03  Unnamed: 6  LS04  \
1       438.66     1           1     1           1     1           1     1   
2       438.65     1           1     1           1     1           1     1   
3       438.64     1           1     1           1     1           1     1   
4       438.63     1           1     1           1     1           1     1   
5       438.62     1           1     1           1     1           1     1   
..         ...   ...         ...   ...         ...   ...         ...   ...   
66      438.01     1           1     0           0     0           0     0   
67      438.00     0           1     0           0     0           0     0   
68      437.99     0           1     0           0     0           0     0   
69      437.98     0           1     0           0     0           0     0   
70      438.97     0           0     0           0     0           0     0   

    Unnamed: 8  LS05  ...  LS29  Unnamed: 58  LS30  Unnamed: 60  LS31  \
1            1     1  ...     1            1     1            1     1   
2            1     1  ...     1            1     1            1     1   
3            1     1  ...     1            1     1            1     1   
4            1     1  ...     1            1     1            1     1   
5            1     1  ...     1            1     1            1     1   
..         ...   ...  ...   ...          ...   ...          ...   ...   
66           0     0  ...     0            0     0            0     0   
67           0     0  ...     0            0     0            0     0   
68           0     0  ...     0            0     0            0     0   
69           0     0  ...     0            0     0            0     0   
70           0     0  ...     0            0     0            0     0   

    Unnamed: 62  LS32  Unnamed: 64  Open  Close  
1             1     1            1   0.0    0.0  
2             1     0            1   0.0    0.0  
3             1     0            1   0.0    0.0  
4             1     0            1   0.0    0.0  
5             1     0            0   0.0    0.0  
..          ...   ...          ...   ...    ...  
66            0     0            0   0.0    0.0  
67            0     0            0   0.0    0.0  
68            0     0            0   0.0    0.0  
69            0     0            0   0.0    0.0  
70            0     0            0   0.0    0.0  

[70 rows x 67 columns]

In [13]:
new_names = ['WaterLevel', 'L1o', 'L1c', 'L2o', 'L2c', 'L3o',
       'L3c', 'L4o', 'L4c', 'L5o', 'L5c', 'L6o',
       'L6c', 'L7o', 'L7c', 'L8o', 'L8c', 'L9o',
       'L9c', 'L10o', 'L10c', 'L11o', 'L11c', 'L12o',
       'L12c', 'L13o', 'L13c', 'L14o', 'L14c', 'L15o',
       'L15c', 'L16o', 'L16c','L17o', 'L17c', 'L18o', 'L18c', 'L19o',
       'L19c', 'L20o', 'L20c', 'L21o', 'L21c', 'L22o',
       'L22c', 'L23o', 'L23c', 'L24o', 'L24c', 'L25o',
       'L25c', 'L26o', 'L26c', 'L27o', 'L27c', 'L28o',
       'L28c', 'L29o', 'L29c', 'L30o', 'L30c', 'L31o',
       'L31c', 'L32o', 'L32c', 'Open', 'Close']

In [14]:
data.columns = new_names

In [15]:
data

WaterLevel  L1o  L1c  L2o  L2c  L3o  L3c  L4o  L4c  L5o  ...  L29o  L29c  \
1       438.66    1    1    1    1    1    1    1    1    1  ...     1     1   
2       438.65    1    1    1    1    1    1    1    1    1  ...     1     1   
3       438.64    1    1    1    1    1    1    1    1    1  ...     1     1   
4       438.63    1    1    1    1    1    1    1    1    1  ...     1     1   
5       438.62    1    1    1    1    1    1    1    1    1  ...     1     1   
..         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
66      438.01    1    1    0    0    0    0    0    0    0  ...     0     0   
67      438.00    0    1    0    0    0    0    0    0    0  ...     0     0   
68      437.99    0    1    0    0    0    0    0    0    0  ...     0     0   
69      437.98    0    1    0    0    0    0    0    0    0  ...     0     0   
70      438.97    0    0    0    0    0    0    0    0    0  ...     0     0   

    L30o  L30c  L31o  L31c  L32o  L32c  Open  Close  
1      1     1     1     1     1     1   0.0    0.0  
2      1     1     1     1     0     1   0.0    0.0  
3      1     1     1     1     0     1   0.0    0.0  
4      1     1     1     1     0     1   0.0    0.0  
5      1     1     1     1     0     0   0.0    0.0  
..   ...   ...   ...   ...   ...   ...   ...    ...  
66     0     0     0     0     0     0   0.0    0.0  
67     0     0     0     0     0     0   0.0    0.0  
68     0     0     0     0     0     0   0.0    0.0  
69     0     0     0     0     0     0   0.0    0.0  
70     0     0     0     0     0     0   0.0    0.0  

[70 rows x 67 columns]

In [16]:
X = data['WaterLevel'].values.reshape(-1, 1)

In [17]:
y1 = data['L1o'].values.reshape(-1, 1).astype(int) 
#y2 = data['L2o'].values.reshape(-1, 1).astype(int) 
#y3 = data['L3o'].values.reshape(-1, 1).astype(int) 
#y4 = data['L4o'].values.reshape(-1, 1).astype(int) 
#y5 = data['L5o'].values.reshape(-1, 1).astype(int) 
#y6 = data['L6o'].values.reshape(-1, 1).astype(int) 
#y7 = data['L7o'].values.reshape(-1, 1).astype(int) 
#y8 = data['L8o'].values.reshape(-1, 1).astype(int) 
#y9 = data['L9o'].values.reshape(-1, 1).astype(int) 
#y10 = data['L10o'].values.reshape(-1, 1).astype(int) 
#y11 = data['L11o'].values.reshape(-1, 1).astype(int) 
#y12 = data['L12o'].values.reshape(-1, 1).astype(int) 
#y13 = data['L13o'].values.reshape(-1, 1).astype(int) 
#y14 = data['L14o'].values.reshape(-1, 1).astype(int) 
#y15 = data['L15o'].values.reshape(-1, 1).astype(int) 
#y16 = data['L16o'].values.reshape(-1, 1).astype(int) 

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
#scaler = StandardScaler()
#X = scaler.fit_transform(X)

In [20]:
model1 = LogisticRegression()
#model2 = LogisticRegression()
#model3 = LogisticRegression()
#model4 = LogisticRegression()
#model5 = LogisticRegression()
#model6 = LogisticRegression()
#model7 = LogisticRegression()
#model8 = LogisticRegression()
#model9 = LogisticRegression()
#model10 = LogisticRegression()
#model11 = LogisticRegression()
#model12 = LogisticRegression()
#model13 = LogisticRegression()
#model14 = LogisticRegression()
#model15 = LogisticRegression()
#model16 = LogisticRegression()

In [21]:
model1.fit(X, y1)
#model2.fit(X, y2)
#model3.fit(X, y3)
#model4.fit(X, y4)
#model5.fit(X, y5)
#model6.fit(X, y6)
#model7.fit(X, y7)
#model8.fit(X, y8)
#model9.fit(X, y9)
#model10.fit(X, y10)
#model11.fit(X, y11)
#model12.fit(X, y12)
#model13.fit(X, y13)
#model14.fit(X, y14)
#model15.fit(X, y15)
#model16.fit(X, y16)

LogisticRegression()

In [22]:
def predict(x):
    prediction = [model1.predict(x)]
                  #model2.predict(x),
                 # model3.predict(x),
                 # model4.predict(x),
                 3 model5.predict(x),
                  model6.predict(x),
                  model7.predict(x),
                  model8.predict(x),
                  model9.predict(x),
                  model10.predict(x),
                  model11.predict(x),
                  model12.predict(x),
                  model13.predict(x),
                  model14.predict(x),
                  model15.predict(x),
                  model16.predict(x)]
    return prediction

In [23]:
scalar_array = np.array([423.0])
reshaped_array = scalar_array.reshape(1, -1)
predict(reshaped_array)

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0])]

In [ ]:
y = data['L2o'].values.reshape(-1, 1).astype(int) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model2 = LogisticRegression()

model2.fit(X_train, y_train)

y_pred = model2.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")